version: 2.1
jobs:
#   build:
#     docker:
#       - image: alpine/git
#     steps:
#       - checkout
  deploy:
     machine: true
#      docker:
#        - image: alpine/git
     steps:
       - run:
           name: git pull
           command: git clone git@github.com:reyhsu/mysql-iii.git;ls -al; cd mysql-iii; ls -al
       - run:
           name: Run Test
           command: cd .circleci; ssh -i ilearning_UAT.pem  ec2-user@18.183.117.67 "sh ls -al"
       - run:
           name: Deploy Over SSH
           command: ssh -i .circleci/ilearning_UAT.pem ec2-user@18.183.117.67 "sh ~/deploy.sh"

 
workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master # 只在 master branch 做
